### ISSUE TITLE
Why "[don't] use a branch argument to git pull or git fetch"

### ISSUE THREAD

**Issue by marcin-kozinski** [SethRobertson/GitBestPractices#2]
Hello Seth,

I would like it very much if you elaborated on a one of the Miscellaneous "don't"s, namely "use a branch argument to git pull or git fetch". I think I get what you mean, but I lack a strong argument to tell other people why not do it. I've also tried to google it, but didn't find anything, however a link to an existing explanation would be great, as well.

Thanks for the great guide!
Best regards
Marcin

**Comment by mmikeww** [comment]
If you want to update your local copy, I can see more confusion arising from using a bare `git pull` because now you don't know whether or not you're syncing with `origin` or `upstream`

**Comment by SethRobertson** [comment]
Well, I personally keep close track of my upstream branch `git branch -vv`.  I've never run into problems with my branch going the wrong place since pretty much that means it never went to the right place.  If you are doing something tricky, fine--at your own risk--but the default for normal users should be the simple version of fetch/pull.
